<style>
  #rl-log-switcher { margin-top: 10px; }
  #log-view-cont label {display:block;}
  #log-pre { background: #BFBFBF; width: 100%; border:1px solid #CCC; margin-top:10px; height: 800px; padding: 10px; }
</style>
<script>
  require(["jquery"], function ($) {
    $(document).ready(function () {
      var tailUrl = "<?php echo $this->getUrl('gallery/logviewer/tail') ?>";
      $rl = $("#rl-log-switcher");
      if ($rl) {
          $rl.change(function() {
              $.ajax({
                url: tailUrl,
                type: 'POST',
                dataType: 'json',
                data: {
                    file: $rl.val()
                },
                complete: function(response) {
                  $logHtml = response.responseJSON.iframeHtml;
                  $("#log-view").html($logHtml);
                }, error: function (xhr, status, errorThrown) {
                    console.log('An error occurred and the log could not be displayed.');
                }
              });
          });
      }
    });
  });
</script>
<div id="log-view-cont">
  <?php echo $this->getLogFilesSelect(); ?>
  <div id="log-view">
    <pre id="log-pre">Please choose a file.</pre>
  </div>
</div>